    /**
     * Districts grouped by Province (Nepal)
     */
    export const DISTRICTS_BY_PROVINCE = {
    'Province 1': [
        'Bhojpur',
        'Dhankuta',
        'Ilam',
        'Jhapa',
        'Khotang',
        'Morang',
        'Okhaldhunga',
        'Panchthar',
        'Sankhuwasabha',
        'Solukhumbu',
        'Sunsari',
        'Taplejung',
        'Terhathum',
        'Udayapur',
    ],

    'Province 2': [
        'Bara',
        'Dhanusha',
        'Mahottari',
        'Parsa',
        'Rautahat',
        'Saptari',
        'Sarlahi',
        'Siraha',
    ],

    'Province 3': [
        'Bhaktapur',
        'Chitwan',
        'Dhading',
        'Dolakha',
        'Kavrepalanchok',
        'Kathmandu',
        'Lalitpur',
        'Makwanpur',
        'Nuwakot',
        'Ramechhap',
        'Rasuwa',
        'Sindhuli',
        'Sindhupalchok',
    ],

    'Province 4': [
        'Baglung',
        'Gorkha',
        'Kaski',
        'Lamjung',
        'Manang',
        'Mustang',
        'Myagdi',
        'Nawalpur',
        'Parbat',
        'Syangja',
        'Tanahun',
    ],

    'Province 5': [
        'Arghakhanchi',
        'Banke',
        'Bardiya',
        'Dang',
        'Gulmi',
        'Kapilvastu',
        'Nawalparasi West',
        'Palpa',
        'Pyuthan',
        'Rolpa',
        'Rupandehi',
    ],

    'Province 6': [
        'Dailekh',
        'Dolpa',
        'Humla',
        'Jumla',
        'Kalikot',
        'Mugu',
        'Rukum West',
        'Salyan',
        'Surkhet',
    ],

    'Province 7': [
        'Achham',
        'Baitadi',
        'Bajhang',
        'Bajura',
        'Dadeldhura',
        'Darchula',
        'Doti',
        'Kailali',
        'Kanchanpur',
    ],
    };
