# Generated by Django 6.0.1 on 2026-01-27 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Vote (Legacy)', 'verbose_name_plural': 'Votes (Legacy)'},
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_votes', to='elections.candidate'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_votes', to='elections.party'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FPTPVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fptp_votes', to='elections.candidate')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.district')),
                ('electoral_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.electoralarea')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.province')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fptp_vote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PRVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.district')),
                ('electoral_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.electoralarea')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_votes', to='elections.party')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.province')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pr_vote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
