# Generated by Django 6.0.1 on 2026-01-27 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_vote_options_alter_vote_candidate_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electoralarea',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='electoralarea',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electoral_areas', to='elections.district'),
        ),
        migrations.AlterUniqueTogether(
            name='electoralarea',
            unique_together={('name', 'district')},
        ),
    ]
