# Generated by Django 6.0 on 2026-01-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_consolidate_votes_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
